server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/takeaway?characterEncoding=UTF-8
    username: root
    password: Z170473781@z
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.zjj.origod.pojo
  mapper-locations: classpath:dao/*Mapper.xml
mybatis-plus:
  type-aliases-package: com.zjj.origod.pojo
  mapper-locations: classpath*:dao/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #    二级缓存
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      #      逻辑删除
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0